import os
os.chdir(r"C:\ZS\gszhushuiSQL")

lines = []
lines.append('// Oracle Dynamic Analysis - separate module to avoid esbuild parsing issues')
lines.append('')
lines.append('type BlockConfig = { name: string; qkdyPattern: string; unit: string };')
lines.append('')
lines.append('const DYNAMIC_ANALYSIS_BLOCKS: BlockConfig[] = [')
lines.append('  { name: "?11", qkdyPattern: "??%", unit: "??????" },')
lines.append('  { name: "?64", qkdyPattern: "?64%", unit: "??????" },')
lines.append('  { name: "?72", qkdyPattern: "?72", unit: "??????" },')
lines.append('  { name: "?????", qkdyPattern: "???N%", unit: "??????" },')
lines.append('  { name: "?????", qkdyPattern: "?????", unit: "??????" },')
lines.append('  { name: "?33", qkdyPattern: "?33", unit: "??????" },')
lines.append('];')
lines.append('')

# Date helper functions
lines.append('function shiftPeriodMonths(startDate: string, endDate: string, monthsOffset: number) {')
lines.append('  const s = new Date(startDate.replace(/\\//g, "-"));')
lines.append('  const e = new Date(endDate.replace(/\\//g, "-"));')
lines.append('  s.setMonth(s.getMonth() + monthsOffset);')
lines.append('  e.setMonth(e.getMonth() + monthsOffset);')
lines.append('  const fmt = (d: Date) => d.toISOString().slice(0, 10).replace(/-/g, "/");')
lines.append('  return { start: fmt(s), end: fmt(e) };')
lines.append('}')
lines.append('')
lines.append('function getPrevYearDecPeriod(startDate: string, endDate: string) {')
lines.append('  const year = parseInt(startDate.slice(0, 4), 10) - 1;')
lines.append('  return { start: year + startDate.slice(4), end: year + endDate.slice(4) };')
lines.append('}')
lines.append('')

# SQL queries using JOIN pattern (matching working queries)
lines.append('const DA_OVERALL_OIL_SQL = `')
lines.append('SELECT ROUND(COUNT(a.jh)/NULLIF(COUNT(DISTINCT a.rq),0),1) AS v0,')
lines.append(' ROUND(SUM(SIGN(a.scsj))/NULLIF(COUNT(DISTINCT a.rq),0),1) AS v1,')
lines.append(' ROUND(SUM(a.rcyl+a.rcsl)/NULLIF(COUNT(DISTINCT a.rq),0),1) AS v2,')
lines.append(' ROUND(SUM(a.rcyl)/NULLIF(COUNT(DISTINCT a.rq),0),1) AS v3,')
lines.append(' ROUND(SUM(a.rcsl)/NULLIF(COUNT(DISTINCT a.rq),0),1) AS v4,')
lines.append(' ROUND(100*SUM(a.rcsl)/NULLIF(SUM(a.rcyl+a.rcsl),0),1) AS v5')
lines.append('FROM dba01 a, daa01 c')
lines.append("WHERE a.rq>=TO_DATE(:s, 'yyyy/mm/dd') AND a.rq<=TO_DATE(:e, 'yyyy/mm/dd')")
lines.append('AND a.jh = c.jh')
lines.append('AND c.qkdy LIKE :q')
lines.append('`;')
lines.append('')

with open("oracle-dynamic-analysis.ts", "w", encoding="utf-8") as f:
    f.write("\n".join(lines[:50]))
print("Part 1 written")
